### PR TITLE
Add an on_connection helper.

### PR DESCRIPTION
**Pull request by adrianb93**
This helper runs a callback under a different database connection.

**Example:**

```php
$tenantPostIds = on_connection('tenantdb', function () {
    return Post::pluck('id');
});
```

This is what is happening:

1. It sets the default connection to the given connection
2. It then runs the callback
3. It swaps back to the previous default connection
4. It returns the callback's return value

It's a very useful helper for multitenant applications. My favourite use for it is this command to run any artisan command on the test database connection:

**Usage:**

```sh
php artisan testdb migrate:fresh
php artisan testdb db:seed
```

**Command:**

```php
<?php

namespace App\Console\Commands;

use InvalidArgumentException;
use Illuminate\Console\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestDb extends Command
{
    protected $signature = 'testdb {targetCommand}';
    protected $description = "Runs the given artisan command on the testing database connection";

    private $testingConnection = 'testing';
    private $blacklistedCommands = ['inspire'];

    public function handle()
    {
        return on_connection($this->testingConnection, function () {
            return $this->call($this->getCommand(), $this->getOptions());
        });
    }

    protected function getCommand()
    {
        return tap($this->argument('targetCommand'), function ($command) {
            if (in_array($command, $this->blacklistedCommands)) {
                throw new InvalidArgumentException(
                    "We do not support [$command] for the [$this->testingConnection] database connection."
                );
            }
        });
    }

    protected function getOptions()
    {
        return collect($this->options())
            ->filter()
            ->map(function ($value, $key) {
                return ["--{$key}" => $value];
            })
            ->collapse()
            ->all();
    }

    public function run(InputInterface $input, OutputInterface $output)
    {
        collect(explode(' ', (string) $input))
            ->filter(function ($token) {
                return strpos($token, '-') === 0;
            })
            ->each(function ($option) {
                $this->addOption($option);
            });

        return parent::run($input, $output);
    }
}

```

### CODE REVIEW

**Comment by calebporzio** [comment]
This is actually pretty dope. Can we rename it to just `connection()`?

**Comment by calebporzio** [comment]
Thanks, I dig it - pulling in.

**Comment by calebporzio** [comment]
Also, just to be clear, you can just do this right?:

```
$postIds = Post::connection('tenant')->pluck('id');
```

**Comment by adrianb93** [comment]
Yes, I'm aware. You could also say that migrate and seed accept a `--database` option. Another example: after calling an artisan command that specifies the database within your code like so:

```php
// Setup the Wordpress database
Artisan::call('migrate:fresh', [
    '--database' => 'wordpress',
    '--path' => 'tests/Servers/Wordpress/database/migrations'
]);

// Uh oh! The default connection is set to 'wordpress'
```

... the default connection stays on the connection given to the command. The connection/on_connection helper makes things a lot easier 😅

```php
on_connection('wordpress', function () {
    Artisan::call('migrate:fresh', [
        '--path' => 'tests/Servers/Wordpress/database/migrations',
    ]);    
});

// The connection is not set to 'wordpress'
```

There are lots of issues like this you can run into when working with multiple database connections. I run into them a lot of them doing integration and multitenant work.

**Comment by calebporzio** [comment]
Ok, thanks for clarifying. I'm going to keep it in the package. Thanks for the contribution!

**Pull request merged**
